//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing.Specificity2.Properties
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Testing.Specificity2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Constraint {0} failed..
        /// </summary>
        internal static string ConstraintFailed
        {
            get
            {
                return ResourceManager.GetString("ConstraintFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not contain &apos;{1}&apos;..
        /// </summary>
        internal static string ContainsFail
        {
            get
            {
                return ResourceManager.GetString("ContainsFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a difference greater than {0}. Expected value: {1}. Actual value: {2}..
        /// </summary>
        internal static string DifferenceLessThanDelta
        {
            get
            {
                return ResourceManager.GetString("DifferenceLessThanDelta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected a difference no greater than {0}. Expected value: {1}. Actual value: {2}..
        /// </summary>
        internal static string DifferenceMoreThanDelta
        {
            get
            {
                return ResourceManager.GetString("DifferenceMoreThanDelta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not start with &apos;{1}&apos;..
        /// </summary>
        internal static string DoesNotStartWith
        {
            get
            {
                return ResourceManager.GetString("DoesNotStartWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicate element found: &lt;{0}&gt;..
        /// </summary>
        internal static string DuplicateElement
        {
            get
            {
                return ResourceManager.GetString("DuplicateElement", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to element count: &lt;{0}&gt;. Actual element count: &lt;{1}&gt;..
        /// </summary>
        internal static string ElementNumbersDoNotMatch
        {
            get
            {
                return ResourceManager.GetString("ElementNumbersDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Element at index {0} is not of the expected type. Expected type: &lt;{1}&gt;. Actual type: &lt;{2}&gt;..
        /// </summary>
        internal static string ElementTypesAtIndexDoNotMatch
        {
            get
            {
                return ResourceManager.GetString("ElementTypesAtIndexDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Element at {0} is (null). Expected type: {1}..
        /// </summary>
        internal static string ElementTypesAtIndexDoNotMatch2
        {
            get
            {
                return ResourceManager.GetString("ElementTypesAtIndexDoNotMatch2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not end with &apos;{1}&apos;..
        /// </summary>
        internal static string EndsWithFail
        {
            get
            {
                return ResourceManager.GetString("EndsWithFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected any value except: &lt;{0}&gt;. Actual: &lt;{1}&gt;..
        /// </summary>
        internal static string Equal
        {
            get
            {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Equality operator not defined for type &apos;{0}&apos;..
        /// </summary>
        internal static string EqualityOperatorNotDefinedForType
        {
            get
            {
                return ResourceManager.GetString("EqualityOperatorNotDefinedForType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong type: {0}. Actual type: {1}..
        /// </summary>
        internal static string EqualTypes
        {
            get
            {
                return ResourceManager.GetString("EqualTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Greater than operator not defined for type &apos;{0}&apos;.
        /// </summary>
        internal static string GreaterThanOperatorNotDefinedForType
        {
            get
            {
                return ResourceManager.GetString("GreaterThanOperatorNotDefinedForType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal operator not defined for type &apos;{0}&apos;.
        /// </summary>
        internal static string GreaterThanOrEqualOperatorNotDefinedForType
        {
            get
            {
                return ResourceManager.GetString("GreaterThanOrEqualOperatorNotDefinedForType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inequality operator not defined for type &apos;{0}&apos;..
        /// </summary>
        internal static string InequalityOperatorNotDefinedForType
        {
            get
            {
                return ResourceManager.GetString("InequalityOperatorNotDefinedForType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; does not match pattern &apos;{1}&apos;..
        /// </summary>
        internal static string IsMatchFail
        {
            get
            {
                return ResourceManager.GetString("IsMatchFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; matches pattern &apos;{1}&apos;..
        /// </summary>
        internal static string IsNotMatchFail
        {
            get
            {
                return ResourceManager.GetString("IsNotMatchFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Less than operator not defined for type &apos;{0}&apos;..
        /// </summary>
        internal static string LessThanOperatorNotDefinedForType
        {
            get
            {
                return ResourceManager.GetString("LessThanOperatorNotDefinedForType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Less than or equal operator not defined for type &apos;{0}&apos;..
        /// </summary>
        internal static string LessThanOrEqualOperatorNotDefinedForType
        {
            get
            {
                return ResourceManager.GetString("LessThanOrEqualOperatorNotDefinedForType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The expected collection contains {0} occurrence(s) of &lt;{1}&gt;. The actual collection contains {2} occurrence(s)..
        /// </summary>
        internal static string MismatchedElements
        {
            get
            {
                return ResourceManager.GetString("MismatchedElements", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple tests failed..
        /// </summary>
        internal static string MultipleTestsFailed
        {
            get
            {
                return ResourceManager.GetString("MultipleTestsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No EquivalenceClasses were specified..
        /// </summary>
        internal static string NoEquivalenceClassesWereSpecified
        {
            get
            {
                return ResourceManager.GetString("NoEquivalenceClassesWereSpecified", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected exception type: &lt;{0}&gt;..
        /// </summary>
        internal static string NoExceptionThrown
        {
            get
            {
                return ResourceManager.GetString("NoExceptionThrown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; contains &apos;{1}&apos;..
        /// </summary>
        internal static string NotContainsFail
        {
            get
            {
                return ResourceManager.GetString("NotContainsFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; ends with &apos;{1}&apos;..
        /// </summary>
        internal static string NotEndsWithFail
        {
            get
            {
                return ResourceManager.GetString("NotEndsWithFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected: &lt;{0}&gt;. Actual: &lt;{1}&gt;..
        /// </summary>
        internal static string NotEqual
        {
            get
            {
                return ResourceManager.GetString("NotEqual", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected type: {0}. Actual type: {1}..
        /// </summary>
        internal static string NotEqualTypes
        {
            get
            {
                return ResourceManager.GetString("NotEqualTypes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string NullValue
        {
            get
            {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PropertyChanged was not raised for {0} when &apos;{1}&apos; was changed..
        /// </summary>
        internal static string PropertyChangedWasNotRaised
        {
            get
            {
                return ResourceManager.GetString("PropertyChangedWasNotRaised", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PropertyChanged was unexpectedly raised for {0} when &apos;{1}&apos; was changed..
        /// </summary>
        internal static string PropertyChangedWasUnexpectedlyRaised
        {
            get
            {
                return ResourceManager.GetString("PropertyChangedWasUnexpectedlyRaised", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to String &apos;{0}&apos; starts with &apos;{1}&apos;..
        /// </summary>
        internal static string StartsWith
        {
            get
            {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing CompareTo with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingCompareToWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingCompareToWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing generic CompareTo with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingGenericCompareToWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingGenericCompareToWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing operator &gt; with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingGreaterThanOperatorWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingGreaterThanOperatorWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing operator &gt;= with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingGreaterThanOrEqualOperatorWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingGreaterThanOrEqualOperatorWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing IEquatable.Equals with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingIEquatableEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingIEquatableEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing operator &lt; with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingLessThanOperatorWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingLessThanOperatorWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing operator &lt;= with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingLessThanOrEqualOperatorWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingLessThanOrEqualOperatorWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing Object.Equals with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingObjectEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingObjectEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing Object.GetHashCode failed with equivalent objects &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string TestingObjectGetHashCodeWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingObjectGetHashCodeWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing operator == with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingOperatorEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingOperatorEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing operator != with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingOperatorNotEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingOperatorNotEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing symmetry of IEquatable.Equals with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingSymmetryOfIEquatableEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingSymmetryOfIEquatableEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing symmetry of Object.Equals with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingSymmetryOfObjectEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingSymmetryOfObjectEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing symmetry of operator == with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingSymmetryOfOperatorEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingSymmetryOfOperatorEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing symmetry of operator != with &apos;{0}&apos; and &apos;{1}&apos; failed..
        /// </summary>
        internal static string TestingSymmetryOfOperatorNotEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingSymmetryOfOperatorNotEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing transitivity of IEquatable.Equals with &apos;{0}&apos;, &apos;{1}&apos; and &apos;{2}&apos; failed..
        /// </summary>
        internal static string TestingTransitivityOfIEquatableEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingTransitivityOfIEquatableEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing transitivity of Object.Equals with &apos;{0}&apos;, &apos;{1}&apos; and &apos;{2}&apos; failed..
        /// </summary>
        internal static string TestingTransitivityOfObjectEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingTransitivityOfObjectEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing transitivity of operator == with &apos;{0}&apos;, &apos;{1}&apos; and &apos;{2}&apos; failed..
        /// </summary>
        internal static string TestingTransitivityOfOperatorEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingTransitivityOfOperatorEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Testing transitivity of operator != with &apos;{0}&apos;, &apos;{1}&apos; and &apos;{2}&apos; failed..
        /// </summary>
        internal static string TestingTransitivityOfOperatorNotEqualsWithValuesFailed
        {
            get
            {
                return ResourceManager.GetString("TestingTransitivityOfOperatorNotEqualsWithValuesFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; did not override the &apos;Object.Equals&apos; method..
        /// </summary>
        internal static string TheTypeDidNotOverrideObjectEqualsMethod
        {
            get
            {
                return ResourceManager.GetString("TheTypeDidNotOverrideObjectEqualsMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; did not override the &apos;Object.GetHashCode&apos; method..
        /// </summary>
        internal static string TheTypeDidNotOverrideObjectGetHashCodeMethod
        {
            get
            {
                return ResourceManager.GetString("TheTypeDidNotOverrideObjectGetHashCodeMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not define equality operators..
        /// </summary>
        internal static string TheTypeDoesNotDefineEqualityOperators
        {
            get
            {
                return ResourceManager.GetString("TheTypeDoesNotDefineEqualityOperators", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; should be sealed as a best practice when implementing &apos;IEquatable&lt;T&gt;&apos;..
        /// </summary>
        internal static string TheTypeShouldBeSealedWhenImplementingIEquatable
        {
            get
            {
                return ResourceManager.GetString("TheTypeShouldBeSealedWhenImplementingIEquatable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exception thrown: &lt;{0}&gt;..
        /// </summary>
        internal static string UnexpectedException
        {
            get
            {
                return ResourceManager.GetString("UnexpectedException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expected exception type: &lt;{0}&gt;. Actual exception type: &lt;{1}&gt;..
        /// </summary>
        internal static string UnexpectedExceptionType
        {
            get
            {
                return ResourceManager.GetString("UnexpectedExceptionType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} failed verification..
        /// </summary>
        internal static string ValueFailedVerification
        {
            get
            {
                return ResourceManager.GetString("ValueFailedVerification", resourceCulture);
            }
        }
    }
}
