//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Specificity")]
[assembly: AssemblyCopyright("Copyright © 2008-2010")]
[assembly: AssemblyVersion("0.2.0.6")]
[assembly: AssemblyFileVersion("0.2.0.6")]


